### ISSUE TITLE
Validation process

### ISSUE THREAD

**Issue by MrYaoH** [ckldan520/DDGCL#2]
Hi, author:
I like your code, but the tensor version makes me feel hard. I have an question about validation process. I want to know whether the queue update operator is performed in validation or testing?

**Comment by ckldan520** [comment]
The negative sample queue is only used in the model training process, and the queue in the validation or testing phase is not involved in inference.

**Comment by MrYaoH** [comment]
> The negative sample queue is only used in the model training process, and the queue in the validation or testing phase is not involved in inference.

Thank you for your reply.
