### ISSUE TITLE
About queue of ‘moco’ module

### ISSUE THREAD

**Issue by MrYaoH** [ckldan520/DDGCL#3]
Hi, author:
I have a confusion about function 'push_queue' in the 106 line of moco_builder.py.  The 'end_queue_ptr' is not normalized, i.e. performing mod operator before using it to update the queue. Whether this operation causes an out-of-bounds problem? What's more, the queue size we use should follow the value accroding to your paper (256) or your code (512)?  I look forward to your reply.

**Comment by ckldan520** [comment]
Hello,  1. When the queue size is an integer multiple of the batch-size, the problem of out-of-bounds will not occur.  “end_queue_ptr” must be less than or equal to the queue size；2. You can directly use the parameters from the paper

**Comment by MrYaoH** [comment]
> Hello, 1. When the queue size is an integer multiple of the batch-size, the problem of out-of-bounds will not occur. “end_queue_ptr” must be less than or equal to the queue size；2. You can directly use the parameters from the paper

Thank you for your reply!
