### ISSUE TITLE
Momentum Update

### ISSUE THREAD

**Issue by MrYaoH** [ckldan520/DDGCL#5]
Hi, author:
Thank you for  your previous answers, and this is beneficial for me. I can understand your code, which is consice and organized, even if it is based on Tensorflow. However, I still have an issue, i.e., momentum update occurs before loss backward or after loss backward？I‘m indeed not good at tensorflow, and I hope you can answer my issue. Thank you very much!

**Comment by ckldan520** [comment]
According to the Ref. MOCO (https://arxiv.org/pdf/1911.05722.pdf,  ), momentum update occurs after loss backward.  You can check 'Algorithm 1' in the paper for the specific process.  But I think the effect should be the same whether it is placed before or after.

**Comment by MrYaoH** [comment]
> According to the Ref. MOCO (https://arxiv.org/pdf/1911.05722.pdf, ), momentum update occurs after loss backward. You can check 'Algorithm 1' in the paper for the specific process. But I think the effect should be the same whether it is placed before or after.

Thank you for your answer. Your work is excellent and charming.
